apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-user-can-view-api-binding
  namespace: tripinsights-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 3d11895f-87c0-4685-8f8b-b381e8d775bc  # web users
  namespace: tripinsights-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-user-can-edit-web-binding
  namespace: tripinsights-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 3d11895f-87c0-4685-8f8b-b381e8d775bc  # web users
  namespace: tripinsights-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-user-can-edit-api-binding
  namespace: tripinsights-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 910bd133-0b8f-41e2-b23e-1bce25936fa2  # api users
  namespace: tripinsights-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-user-can-view-web-binding
  namespace: tripinsights-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 910bd133-0b8f-41e2-b23e-1bce25936fa2  # api users
  namespace: tripinsights-web
