apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
  namespace: openhack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: registryrfq6839.azurecr.io/tripviewer:v1.0
        imagePullPolicy: Always
        name: tripviewer
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "trips.openhack"
        - name: USERPROFILE_API_ENDPOINT
          value: "userprofile.openhack"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"



