apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4293cc82-3323-41cb-bf31-9f4c7372238a"
    keyvaultName: "aks2-kv"
    objects: |
      array:
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME              
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-FQDN
          objectAlias: SQL_SERVER              
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD             
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER              
          objectType: secret
          objectVersion: ""
    tenantId: "TENANT"
