apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "false"
    keyvaultName: "aks2-kv"
    objects: |
      array:
        - |
          objectName: SQL-DBNAME              
          objectType: secret
          objectVersion: ""
          objectName: SQL-FQDN              
          objectType: secret
          objectVersion: ""
          objectName: SQL-PASSWORD             
          objectType: secret
          objectVersion: ""
          objectName: SQL-USER              
          objectType: secret
          objectVersion: ""
    tenantId: "TENANTID"
