apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryanm5076.azurecr.io/poi:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminaNm5076"
        - name: SQL_PASSWORD
          value: "tP4rd6Zs3"
        - name: SQL_SERVER
          value: "sqlserveranm5076.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
