apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-java
  name: user-java
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - image: registryrfq6839.azurecr.io/user-java:v1.0
          imagePullPolicy: Always
          name: user-java
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
