apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trips
  name: trips
  namespace: openhack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: registryrfq6839.azurecr.io/trips:chris
        imagePullPolicy: Always
        name: trips
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserverrfq6839.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlauth
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlauth
              key: password
        - name: OPENAPI_DOCS_URI
          value: "http://localhost"
        - name: DEBUG_LOGGING
          value: "true"
