apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poi
  name: poi
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - image: registryrfq6839.azurecr.io/poi:v1.0
          imagePullPolicy: Always
          name: poi
          ports:
            - containerPort: 80
                  volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"