apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofile
  name: userprofile
  namespace: openhack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - image: registryrfq6839.azurecr.io/userprofile:v1.0
        imagePullPolicy: Always
        name: userprofile
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserverrfq6839.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlauth
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlauth
              key: password
