apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofile
  name: userprofile
  namespace: openhack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - image: registryrfq6839.azurecr.io/userprofile:v1.0
        imagePullPolicy: Always
        name: userprofile
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: SQL-USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SQL-PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: SQL-FQDN
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: SQL-DBNAME
   volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
